name: example
description: Demonstrates how to use the emerald_logging_flutter plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  emerald_logging_flutter:
    path: ../

  logging: ^1.2.0

flutter:
  uses-material-design: true
