name: emerald_logging_flutter
description: >-
  Flutter extension for the logging package.
  This package provides a simple tool for logging messages 
  in your applications and a set of additional utilities.
  ELogger class is a lot closer to the original logging class.
version: 1.2.0
homepage: https://github.com/wolfe719/emerald_logging_flutter
repository: https://github.com/wolfe719/emerald_logging_flutter
documentation: https://github.com/wolfe719/emerald_logging_flutter
platforms:
  android:
  ios:
screenshots:
  - description: "This screenshot shows the log console UI in dark mode."
    path: doc/static/log_console_dark.png
  - description: "This screenshot shows the log console UI in light mode."
    path: doc/static/log_console_light.png
topics:
  - logging
  - console
  - extension

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.2.0
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
